spring.application.name=demo

# DB ?? ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Seoul
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


gemini:
    api:
        key: ${GEMINI_API_KEY}
        #아직 미수정
        #url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
